### ISSUE TITLE
License

### ISSUE THREAD

**Issue by danoff** [jakobib/hshoa2014#1]
Hi! Thanks for your great work here!!

What is the license of this repo? I'd like to use it as an example in an upcoming talk on how teachers can use GitHub to manage their Open Educational Resources.

**Comment by nichtich** [comment]
CC-BY-SA. I'll add a LICENSE.md Thanks!

On 2. Februar 2016 10:16:44 MEZ, Charlie Danoff notifications@github.com wrote:

> Hi! Thanks for your great work here!!
> 
> What is the license of this repo? I'd like to use it as an example in
> an upcoming talk on how teachers can use GitHub to manage their Open
> Educational Resources.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jakobib/hshoa2014/issues/1

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by danoff** [comment]
Great! Thanks!!
